Complete maps task
TimofeiN/ru-study-python pull request #2
Opened 2023-04-15 09:16 UTC by TimofeiN

2023-04-16 17:36 UTC, aleksandr-semenov-dbp requested changes

2023-04-16 17:36 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +        avg_rating = reduce(lambda x, y: x + y, ratings_list) / len(ratings_list)
зачем reduce() это же просто sum()

2023-04-16 17:36 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +            countries = dict_obj["country"].split(",")
split() неэффективно использовать для подсчета запятых

2023-04-17 10:50 UTC, aleksandr-semenov-dbp requested changes

2023-04-17 10:50 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +            countries = country_counter(dict_obj["country"])[","]
Очень оригинально, но еще более неэффективно. Используй string.count()

2023-04-17 13:18 UTC, TimofeiN commented on maps/maps.py
> +            countries = country_counter(dict_obj["country"])[","]
В почте не сразу увидел, что есть новый комментарий к ПР. Исправил

2023-04-18 10:28 UTC, aleksandr-semenov-dbp requested changes

2023-04-18 10:28 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +            letter_count = counter["и"]
и здесь тоже

2023-04-18 16:28 UTC, aleksandr-semenov-dbp approved these changes

2023-04-20 09:12 UTC, merged